name: Test and lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm test

  package_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run package
      - name: Ensure that code has been packaged and committed
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            git status --porcelain dist/
            echo -e "\nPlease run 'npm run package' and commit the results"
            exit 1
          fi

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Install vultr-cli
        id: install
        uses: ./

      - name: Verify installation
        shell: bash
        run: vultr-cli version | grep -F "${{ steps.install.outputs.version }}"

  test_custom_version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Install vultr-cli
        uses: ./
        with:
          version: 3.0.0

      - name: Verify installation of correct version
        shell: bash
        run: vultr-cli version | grep -F "3.0.0"
